### ISSUE TITLE
`positions` not found

### ISSUE THREAD

**Issue by cortner** [cortner/SKTB.jl#13]
```
using JuLIP, JuLIP.ASE, TightBinding
TB = TightBinding;
NRLTB = TightBinding.NRLTB;

β = 30.0
at = bulk("C", pbc = true, cubic = true)
bzq = TB.MPGrid(at, (4,4,4))
nrltb = TB.NRLTB.NRLTBModel(:C, TB.FermiDiracSmearing(β), bzquad = bzq, cutoff = :original);

TB.spectrum(nrltb,at)
```

this creates an exception on @ettersi 's linux laptop. (both in release and master of JuLIP)

**Comment by cortner** [comment]
I can't reproduce it on Kaiju.

**Comment by cortner** [comment]
@ettersi : Could you please do the following: 
* pull the latest master of `TightBinding`
* `Pkg.rm("JuLIP"); Pkg.add("JuLIP")`
* `JULIPVISUALISE = false`
then run this script again and report back here the error message?

**Comment by ettersi** [comment]
I deleted both JuLIP and TightBinding (TightBinding depends on JuLIP, so `Pkg.rm("JuLIP")` does not actually remove JuLIP) and reinstalled, using `Pkg.clone("git@github.com:cortner/TightBinding.jl.git")` for TightBinding. The first time I forgot typing `JULIPVISUALISE = false` and got the same error message as before:

```
ERROR: KeyError: key "positions" not found
 in getindex(::PyCall.PyObject, ::String) at /home/simon/.julia/v0.5/PyCall/src/PyCall.jl:268
 in length at /home/simon/.julia/v0.5/JuLIP/src/ASE.jl:113 [inlined]
 in ndofs at /home/simon/.julia/v0.5/TightBinding/src/types.jl:68 [inlined]
 in band_structure(::TightBinding.TBModel{TightBinding.NRLTB.NRLHamiltonian{4,Function},TightBinding.FermiDiracSmearing}, ::JuLIP.ASE.ASEAtoms) at /home/simon/.julia/v0.5/TightBinding/src/calculators.jl:216
 in spectrum(::TightBinding.TBModel{TightBinding.NRLTB.NRLHamiltonian{4,Function},TightBinding.FermiDiracSmearing}, ::JuLIP.ASE.ASEAtoms) at /home/simon/.julia/v0.5/TightBinding/src/calculators.jl:229

```

Then I removed and added again, made sure I added the `JULIPVISUALISE`  line and ran again, and now it crashes with 

```
Intel MKL FATAL ERROR: Cannot load /home/simon/anaconda3/lib/python3.5/site-packages/numpy/core/../../../../libmkl_core.so.
```

**Comment by ettersi** [comment]
I suspect something is wrong with my Python/ASE installation, but I have no idea how to check that.

**Comment by cortner** [comment]
this is a bigger request: is there a way to switch to Python 2.7?

**Comment by ettersi** [comment]
Is that what you are using?

**Comment by cortner** [comment]
yes

**Comment by cortner** [comment]
```
Sunrise:~ ortner$ ipython
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17)
Type "copyright", "credits" or "license" for more information.
```

**Comment by ettersi** [comment]
Ok, I'll look into it

**Comment by ettersi** [comment]
It works! Hard to tell what really caused the issue, though, because changing the Python version also required me to reinstall ASE and matscipy. In any case, it seems to work so no point digging deeper for now.

**Comment by cortner** [comment]
I'm relieved. And to be on the safe side I just pushed an update to JuLIP that gives a warning if the Python version is > 2.7.x.
