### ISSUE TITLE
Parallelisation

### ISSUE THREAD

**Issue by cortner** [cortner/SKTB.jl#5]
I'd like to optimise the `partial_energy` function in `TightBinding.Contour`, e.g. example just parallelising.
 
 Since the case of evaluating the hamiltonian entries is really quite high, it seems reasonable to first evaluate and store the residuals (or maybe the LU factorisations) on each quadrature point. But even for moderate systems this goes into the 10s of GB.  Here is where my lack of HPC expertise is a problem: what are reasonable amounts of data to store and recall as needed?  what if we run this on a small cluster - do we then count "how much memory per processor / node"?

**Comment by ettersi** [comment]
Wenn Du willst, können wir das morgen oder am Freitag besprechen.

Zur Energieberechnung sehe ich folgende Optimierungsmöglichkeiten:
  - Verwende sparse LU (ich vermute, das machst Du bereits?)
  - Parallelisierung
  - linear scaling LU (wäre einiges an Arbeit. Mehr der Vollständigkeit halber aufgelistet)

Ich verstehe nicht ganz, was site_grad_inner genau berechnet, und weshalb Du den Hamiltonian mehrfach auswerten musst. Hier wäre es vielleicht 
nützlich, kurz zusammen zu sitzen.

Liebe Grüsse,
Simon

**Comment by cortner** [comment]
Hi Simon,

Vielen Dank - ich sehe dass ich Freitag zeit machen kann und melde mich. 

	Christoph

**Comment by cortner** [comment]
looks like the simplest solution is to simply store all the D_{yj} H matrices, and then probably parallelise over the contour.

**Comment by cortner** [comment]
This is now achieved via the `SparseSKHGrad` data structure.
